### PR TITLE
Svg text background fix

### PR DESCRIPTION
**Pull request by lvcarx**
This fixes 2 issues:

- The Ubuntu Mono font wasn't loaded correctly in an exported svg file (it is now directly embedded into the document)
- The text background now has the correct dimensions (it was too long before, because of differences between svg and java font rendering)

### CODE REVIEW

**Comment by hageldave** [comment]
Since we are now embedding the font into the SVG file, I think we are effectively distributing the font. This may require us to include a copyright notice. 
https://ubuntu.com/legal/font-licence
The good thing is that we are allowed to distribute the font freely, but we probably need to figure out how we include the license.

**Comment by lvcarx** [comment]
I committed two different proposals on how to include the license (directly as text and via a link). We should discuss which solution is the best.

**Comment by lvcarx** [comment]
As discussed, the whole licence is included again. There is a comment for each paragraph of the licence.

**Comment by hageldave** [comment]
I refactored the code, and also changed the css part to be a CDATA section instead of the regular text content.
i.e.:
```java
CDATASection cdatasection_fontface_css = document.createCDATASection(fontface_css);
styleElement.appendChild(cdatasection_fontface_css);
```
instead of 
```java
styleElement.setTextContent(fontface_css);
```
because text content will be normalized later and then characters like `"` or `'` will be replaced by `&quot;` or `&apos;`. CDATA sections stay untouched. [This example](https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/id) also uses CDATA to escape the css block.

Since I'm on Ubuntu right now, the font is installed by default and I'm not sure if these changes work. Still needs to be confirmed on a different machine/OS.

**Pull request merged**
